// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:180420387971:web:b4c69f99c954bce6a627b6',
    messagingSenderId: '180420387971',
    projectId: 'zomber-6307f',
    authDomain: 'zomber-6307f.firebaseapp.com',
    storageBucket: 'zomber-6307f.firebasestorage.app',
    measurementId: 'G-RHSBRVCCJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:180420387971:android:3e88edd9e2d1d172a627b6',
    messagingSenderId: '180420387971',
    projectId: 'zomber-6307f',
    storageBucket: 'zomber-6307f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:180420387971:ios:de7c8af5a54c9ce0a627b6',
    messagingSenderId: '180420387971',
    projectId: 'zomber-6307f',
    storageBucket: 'zomber-6307f.firebasestorage.app',
    iosBundleId: 'com.example.eepediaz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:180420387971:ios:de7c8af5a54c9ce0a627b6',
    messagingSenderId: '180420387971',
    projectId: 'zomber-6307f',
    storageBucket: 'zomber-6307f.firebasestorage.app',
    iosBundleId: 'com.example.eepediaz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:180420387971:web:32897f0642e4b6a6a627b6',
    messagingSenderId: '180420387971',
    projectId: 'zomber-6307f',
    authDomain: 'zomber-6307f.firebaseapp.com',
    storageBucket: 'zomber-6307f.firebasestorage.app',
    measurementId: 'G-S71MC106C1',
  );

}
